taco:
  orders:
    pageSize: 10

spring:
  profiles:
    active:
      - dev

  data:
    rest:
      basePath: /api

  jms:
    template:
      default-destination: tacocloud.order.queue

  rabbitmq:
    template:
      exchange: tacocloud.orders
      routing-key: kitchens.central
      receive-timeout: 30000

  kafka:
    template:
      default-topic: tacocloud.orders.topic